export function treasureHuntFragmentCode(order: number) {
  return `yc-fragment-${String(order).padStart(2, '0')}`
}

export const TREASURE_HUNT_QUIZ_SEED = [
  {
    fragmentOrder: 1,
    question: 'Siapa orang pertama dalam Alkitab yang disebut "penuh dengan Roh Allah"?',
    optionA: 'Musa',
    optionB: 'Daud',
    optionC: 'Bezaleel',
    optionD: 'Yosua',
    correctAnswer: 'C',
    explanation: 'Keluaran 31:1-5 — Bezaleel dipenuhi Roh Allah untuk membuat perlengkapan tabut.',
  },
  {
    fragmentOrder: 2,
    question: 'Ketika Yesus memberi makan 5.000 orang, siapa yang membawa lima roti dan dua ikan?',
    optionA: 'Petrus',
    optionB: 'Andreas',
    optionC: 'Filipus',
    optionD: 'Seorang anak kecil',
    correctAnswer: 'D',
    explanation: 'Yohanes 6:9 — seorang anak kecil yang membawa roti dan ikan.',
  },
  {
    fragmentOrder: 3,
    question: 'Siapa yang tidur di dalam perahu ketika badai besar terjadi?',
    optionA: 'Petrus',
    optionB: 'Yohanes',
    optionC: 'Yesus',
    optionD: 'Yakobus',
    correctAnswer: 'C',
    explanation: 'Markus 4:38 — Yesus tidur di atas bantal di bagian belakang perahu.',
  },
  {
    fragmentOrder: 4,
    question: 'Siapa orang yang naik ke surga tanpa mengalami kematian?',
    optionA: 'Elia',
    optionB: 'Henokh',
    optionC: 'Keduanya benar',
    optionD: 'Musa',
    correctAnswer: 'C',
    explanation: 'Henokh (Kejadian 5:24) dan Elia (2 Raja-raja 2:11) naik ke surga tanpa mati.',
  },
  {
    fragmentOrder: 5,
    question: 'Apa mukjizat pertama yang dicatat dilakukan Yesus?',
    optionA: 'Menyembuhkan orang buta',
    optionB: 'Mengusir setan',
    optionC: 'Mengubah air menjadi anggur',
    optionD: 'Memberi makan 5.000 orang',
    correctAnswer: 'C',
    explanation: 'Yohanes 2:1-11 — air diubah menjadi anggur di Kana.',
  },
  {
    fragmentOrder: 6,
    question:
      'Dalam perumpamaan Orang Samaria yang Baik Hati, siapa yang lewat lebih dulu sebelum orang Samaria datang?',
    optionA: 'Imam lalu orang Lewi',
    optionB: 'Orang Lewi lalu imam',
    optionC: 'Murid Yesus lalu imam',
    optionD: 'Pedagang lalu orang Lewi',
    correctAnswer: 'A',
    explanation: 'Lukas 10:31-32 — imam lewat dulu, lalu orang Lewi.',
  },
  {
    fragmentOrder: 7,
    question: 'Ketika Daud melawan Goliat, berapa batu yang dia ambil dari sungai?',
    optionA: '1',
    optionB: '3',
    optionC: '5',
    optionD: '7',
    correctAnswer: 'C',
    explanation: '1 Samuel 17:40 — Daud mengambil lima batu licin dari sungai.',
  },
  {
    fragmentOrder: 8,
    question: 'Dalam kisah Yunus, siapa yang sebenarnya "menyuruh" ikan besar menelan Yunus?',
    optionA: 'Laut yang mengamuk',
    optionB: 'Ikan itu sendiri',
    optionC: 'Tuhan',
    optionD: 'Para pelaut',
    correctAnswer: 'C',
    explanation: 'Yunus 1:17 — atas penentuan TUHAN datanglah seekor ikan besar.',
  },
] as const
